name: CI

on:
  push:
    branches: [main, professionals]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: "read"
      id-token: "write"

    steps:
      - uses: "actions/checkout@v3"

      - id: "auth"
        name: "Authenticate to Google Cloud"
        uses: "google-github-actions/auth@v1"
        with:
          workload_identity_provider: "projects/365520006193/locations/global/workloadIdentityPools/sensitive-dogs/providers/sensitive-dogs"
          service_account: "sensitive-github-actions@workload-identity-pools-385416.iam.gserviceaccount.com"

      - name: Setup - gcloud / gsutil
        uses: google-github-actions/setup-gcloud@v1

      - id: "gcloud-test"
        name: "gcloud-test"
        run: |-
          gcloud secrets versions access "latest" --secret "my-secret"

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Use Node.js 18.x
        uses: actions/setup-node@v2
        with:
          node-version: 18.x

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Type check
        run: yarn type-check

      - name: Lint
        run: yarn lint

      - name: Test
        run: yarn test
