name: Deploy to Firebase Hosting on demand
"on": [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: production
    permissions:
      contents: "read"
      id-token: "write"

    steps:
      - uses: "actions/checkout@v3"

      - id: "auth"
        name: "Authenticate to Google Cloud"
        uses: "google-github-actions/auth@v1"
        with:
          token_format: "access_token"
          workload_identity_provider: "${{ secrets.GCS_WORKLOAD_IDENTITY_PROVIDER }}"
          service_account: "${{ secrets.GCS_SERVICE_ACCOUNT }}"

      - name: Setup - gcloud / gsutil
        uses: google-github-actions/setup-gcloud@v1

      - name: Use Node.js 20.x
        uses: actions/setup-node@v2
        with:
          node-version: 20.x

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Type check
        run: yarn type-check

      - name: Lint
        run: yarn lint

      - name: Test
        run: yarn test

      - name: Build
        env:
          CI: "true"
          IMAGES_FOLDER_ID: ${{ secrets.IMAGES_FOLDER_ID }}
          ARTICLES_FOLDER_ID: ${{ secrets.ARTICLES_FOLDER_ID }}
          DATA_FOLDER_ID: ${{ secrets.DATA_FOLDER_ID }}
        run: yarn build

      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_SENSITIVE_DOGS }}"
          channelId: live
          projectId: sensitive-dogs
